server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog-dev
    username: usr-esp-catalog
    password: pwd-esp-catalog
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka  